SUPABASE_URL = "https://cwazbepluvvssyklqsis.supabase.co"
SUPABASE_KEY = "sb_publishable_i4qgKpnIevL0170xFL83aw_iccShMjz"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN3YXpiZXBsdXZ2c3N5a2xxc2lzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTE4ODM1MSwiZXhwIjoyMTAwNzY0MzUxfQ.1ZfywEreDIT8_AxJFsO67PqwvJgtPQKVjIlg6Kt6rok"

ADMIN_USERNAME = "admin"
ADMIN_PASSWORD = "timsosial1800"